services:
  nginx:
    image: nginx:1.29
    container_name: nginx-container
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./credentials/cert.pem:/etc/nginx/certs/cert.pem
      - ./credentials/cert.key:/etc/nginx/certs/cert.key
    ports:
      - "8090:8090" # Auth
    networks:
      - internal
    depends_on:
      keycloak:
        condition: service_started

  keycloak:
    image: quay.io/keycloak/keycloak:26.5
    container_name: keycloak-container
    command: start
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin

      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres-container:5432/kc_db
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=postgres

      - KC_HOSTNAME=https://localhost:8090
      - KC_HOSTNAME_ADMIN=https://localhost:8090
      - KC_PROXY_HEADERS=xforwarded
      - KC_HTTP_ENABLED=true

    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - internal
    volumes:
      - ./keycloak-providers:/opt/keycloak/providers
      - ./keycloak-themes:/opt/keycloak/themes

  postgres:
    image: postgres:18
    container_name: postgres-container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=kc_db
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres-db-data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d kc_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  #  This is for cache backend data
  redis:
    image: redis:8
    container_name: redis-container
    networks:
      - internal
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep -q PONG"]
      interval: 10s
      timeout: 5s
      retries: 5

  spring:
    container_name: spring-container
    build:
      context: ./spring
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - internal
    depends_on:
      mysql:
        condition: service_healthy
      seaweedfs-s3:
        condition: service_started
      redis:
        condition: service_healthy
      keycloak:
        condition: service_started

  mysql:
    image: mysql:9.6
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql:ro
      - mysql-db-data:/var/lib/mysql
    ports:
      - "127.0.0.1:3306:3306"
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -proot --silent"]
      interval: 10s
      timeout: 5s
      retries: 10

  seaweedfs-s3:
    container_name: seaweedfs-s3
    image: chrislusf/seaweedfs:4.23
    command: server -s3 -s3.config=/etc/seaweedfs/s3.json
    volumes:
      - ./credentials/seaweedfs/s3.json:/etc/seaweedfs/s3.json:ro
      - seaweedfs-s3-data:/data
    ports:
      - "9000:8333"  # S3 API
      - "9333:9333"  # Master
      - "8888:8888"
    networks:
      - internal

volumes:
  mysql-db-data:
  postgres-db-data:
  redis-data:
  seaweedfs-s3-data:

networks:
  internal:
    driver: bridge
